### ISSUE TITLE
suggestion: black formatting suggest

### ISSUE THREAD

**Issue by tsuyoshicho** [reviewdog/action-black#5]
## suggestion

black skip github-pr-review reviewdog's report.
That's all right.

And I suggest reporting fixed result suggestion support.

see https://github.com/reviewdog/reviewdog#diff

```shell
$ black --help


  --diff                          Don't write the files back, just output a
                                  diff for each file on stdout.
```

process: `--diff` alternate `--check` and format `diff` or fix and git diff report.

How about trying this?

**Comment by rickstaa** [comment]
@tsuyoshicho That indeed looks like a way to both create a more informative output and add support for the `github-pr-review` reporter. I am myself not familiar with piping  the reviewdog diff argument other than invoking it using `--diff="git diff master". tried doing this using the following syntaxes:

`black --diff . 2>&1 | reviewdog -name="black" -f=diff -f.diff.strip=0 -reporter=github-pr-check`
`black --diff . | reviewdog -name="black" -f=diff -f.diff.strip=0 -reporter=github-pr-check`

But this doesn't seem to work on my local test environment (using `reporter=local`). I keep getting a `failed to get diff error`.

The diff report appears to be posted on the stdin while the black formatter output is posted on the std_err. If I understand it correctly you want the `-f=black` format to handle a message of which files are formatted and the `-f=diff` to create comments for the diferences black would apply. Or is the `-f=diff` option enough to do both. Feel free to create a pull request.

**Comment by tsuyoshicho** [comment]
Okay,

I try patch and PR. please wait a little.

**Comment by rickstaa** [comment]
@tsuyoshicho No hurries. Thanks a lot for the great idea. Let me know if you need any help.

**Comment by rickstaa** [comment]
Seems to work perfectly (see [this new test](https://github.com/rickstaa/action-test-repo/pull/2)). Thanks for the amazing feature ✨ !
