### ISSUE TITLE
Allow user to select the version of black to mitigate the effects of braking update of black

### ISSUE THREAD

**Issue by meltingrabbit** [reviewdog/action-black#58]
black can be updated brakingly in every year; 

ref: https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy
> The first release in a new calendar year may contain formatting changes, although these will be minimised as much as possible. This is to allow for improved formatting enabled by newer Python language syntax as well as due to improvements in the formatting logic.

As a result, existing CIs may not be able to be passed, like https://github.com/ut-issl/c2a-core/actions/runs/4061389376/jobs/6991355742

**Comment by rickstaa** [comment]
> black can be updated brakingly in every year;
> 
> ref: https://black.readthedocs.io/en/stable/the_black_code_style/index.html#stability-policy
> 
> > The first release in a new calendar year may contain formatting changes, although these will be minimised as much as possible. This is to allow for improved formatting enabled by newer Python language syntax as well as due to improvements in the formatting logic.
> 
> As a result, existing CIs may not be able to be passed, like https://github.com/ut-issl/c2a-core/actions/runs/4061389376/jobs/6991355742

Thanks for letting me know. Do you experience any problems right now with the action? Feel free to submit [a fix](https://github.com/reviewdog/action-black/pulls).

**Comment by gabmartinez** [comment]
@rickstaa @meltingrabbit I created the #59 PR. Please review it and let me know any feedback.

Thanks!

**Comment by meltingrabbit** [comment]
Thanks for replying to my issue.

> This is a composite action so you can change the black version installed in steps preceding the action-black action.

We have noticed that as well, and there are no problems now.

**Comment by sksat** [comment]
The main reason for specifying the `black` version is to avoid a situation where CI fails even though there are no diffs at all. And, as mentioned above, this is no problem if explicitly installed in the previous step.

In addition, such versioning should be done in separate files such as `requirements.txt` or `Pipfile`, and there are multiple ecosystems for installing such Python libraries. So, when users want to specify `black` version, the decision of how to install should be left to the user.

I think the example workflow in README may need to be modified to make it easier for users to understand this situation.

**Comment by gabmartinez** [comment]
@sksat that's a good approach. I tested it this morning and it's working correctly. I'll close my PR in favor of yours.

Thanks @sksat 🥇

**Comment by rickstaa** [comment]
Closed by #60 @sksat thanks for your contribution!
