### ISSUE TITLE
Add repository description

### ISSUE THREAD

**Issue by rickstaa** [reviewdog/action-black#9]
I just noticed that this repo doesn't have a repository description. Can someone with admin rights @mattn, @haya14busa please add that or give me admin rights to the repository.

**Comment by haya14busa** [comment]
Thanks!

I added the admin role as you're the original owner of the repo.
Also, I added the maintainer role to action-maintainer team, which should be basically sufficient to maintain repos including changing the description.
action-maintainer team actually should have maintainer role for all action repos.

Hmm... probably we should document the required steps when transferring the repos not to forget something.

**Comment by rickstaa** [comment]
@haya14busa Thanks a lot! I think it was just a gap in my understanding of what would happen when I tranfered the repository to a organization. I expected to be automatically added as a action-maintainer.
